### ISSUE TITLE
BulletTime doesn't reset its timer between uses.

### ISSUE THREAD

**Issue by GigabyteGamer** [Eveeko/bullegachi#2]
![image](https://github.com/user-attachments/assets/b9c60792-2b95-4b6c-afad-c2d8759ad1c3)
_After second use of BulletTime for a given run. BulletTime's timer is now at 1:11h instead of the default 1:20h_

The timer doesn't reset between separate uses of the BulletTime item.

**Comment by Eveeko** [comment]
For clarification, you use bulletTime once and it goes to 1:20h, it expires. then you use a new bulletTime and its timer is at 1:11h

**Comment by GigabyteGamer** [comment]
> For clarification, you use bulletTime once and it goes to 1:20h, it expires. then you use a new bulletTime and its timer is at 1:11h?

Apologies, it seems I didn't notice a 2nd BulletTime was not consumed. Seems to work as intended aside from some visual artifacting.

**Comment by Eveeko** [comment]
Could you please attach the scenario that causes such visual errors to occur?

**Comment by GigabyteGamer** [comment]
https://github.com/user-attachments/assets/f30bd8fd-169c-4be8-9440-fded0b693174

The recording is at a low framerate, but the 'paused VHS' effect doesn't seem to be cycling properly.

**Comment by Eveeko** [comment]
> 2024-10-18.22-05-36.mp4 
> The recording is at a low framerate, but the 'paused VHS' effect doesn't seem to be cycling properly.

Oh! no that *jitter* effect is intentionally made to mimick the way old VHS players would cause a distortion effect when the tape is paused. (referenced as "tracking distortion")

**Comment by GigabyteGamer** [comment]
I see, false alarm then. Thank you.
