### ISSUE TITLE
Reset save file on a major version number change.

### ISSUE THREAD

**Issue by Eveeko** [Eveeko/bullegachi#3]
## Integrate into the auto-updater for notifying and into the client itself a set of methods that resets the current save data back to default upon a major version number increase.
> ie: 2.x.x => 3.x.x

This prevents conflicts with prior save data structures, gives control over local save data resets (in-case a save data structure change is made) and also allows major additions to be experienced in a situation where they might otherwise not be able to be due to progress in the current save state.

**Comment by GigabyteGamer** [comment]
This would be a good feature for Bulletgachi. Resetting progress is a good way to allow the user to re-experience the entirety of the intended progression and experience. Of course, there should be ample prior notice and preferable, the user should be able to choose whether to update or not.

**Comment by Eveeko** [comment]
> This would be a good feature for Bulletgachi. Resetting progress is a good way to allow the user to re-experience the entirety of the intended progression and experience. Of course, there should be ample prior notice and preferable, the user should be able to choose whether to update or not.

I full agree, I was thinking along the lines of adding a bolded text under the version number when the update screen is show, to indicate a save reset would occur. something along the lines of say: "RESETS SAVE!"

This would allow the user just to continue on for now and finish out their save before they decide to wipe for the new major update.
